# Generated by Django 3.0 on 2019-12-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EltecNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardId', models.IntegerField()),
                ('num', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('link', models.CharField(max_length=300)),
            ],
        ),
    ]
