# Generated by Django 3.0 on 2019-12-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eltec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eltecnotice',
            name='category',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
