# Generated by Django 3.0 on 2019-12-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_category', models.IntegerField(choices=[(0, 'Common'), (1, 'Eltec')])),
                ('boardId', models.IntegerField()),
                ('board_type', models.IntegerField(choices=[(0, 'Common'), (1, 'Category'), (2, 'Non-Category')])),
                ('base_url', models.CharField(max_length=300)),
                ('next_url', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=20)),
                ('saved_latest', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_category', models.IntegerField(choices=[(0, 'Common'), (1, 'Eltec')], db_index=True)),
                ('boardId', models.IntegerField()),
                ('num', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=5, null=True)),
                ('date', models.DateField()),
                ('url', models.CharField(max_length=300)),
                ('push', models.BooleanField(default=False)),
            ],
        ),
    ]
