# Generated by Django 3.0 on 2019-12-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='saved_latest',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
