# Generated by Django 3.0 on 2019-12-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20191229_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='saved_latest',
            field=models.IntegerField(default=0),
        ),
    ]
