# Generated by Django 3.0 on 2019-12-29 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20191229_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='boardId',
            new_name='board_id',
        ),
    ]
