# Generated by Django 3.0 on 2019-12-29 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20191229_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='boardId',
            new_name='board_id',
        ),
    ]
